import type { TimerSettings, Quote } from '@/types';

export const DEFAULT_TIMER_SETTINGS: TimerSettings = {
  focusDuration: 25,
  shortBreakDuration: 5,
  longBreakDuration: 15,
  longBreakInterval: 4,
};

export const QUOTES: Quote[] = [
  { id: 'q1', text: 'Le succès n\'est pas final, l\'échec n\'est pas fatal : c\'est le courage de continuer qui compte.', author: 'Winston Churchill' },
  { id: 'q2', text: 'La seule façon de faire du bon travail est d\'aimer ce que vous faites.', author: 'Steve Jobs' },
  { id: 'q3', text: 'Chaque jour est une nouvelle chance de changer votre vie.', author: 'Inconnu' },
  { id: 'q4', text: 'Le secret du changement, c\'est de concentrer toute votre énergie non pas à lutter contre le passé, mais à construire l\'avenir.', author: 'Socrate' },
  { id: 'q5', text: 'La discipline est le pont entre les objectifs et la réussite.', author: 'Jim Rohn' },
  { id: 'q6', text: 'Ce n\'est pas la charge qui vous fait tomber, c\'est la façon dont vous la portez.', author: 'Lou Holtz' },
  { id: 'q7', text: 'Soyez le changement que vous souhaitez voir dans le monde.', author: 'Gandhi' },
  { id: 'q8', text: 'La vie est ce qui se passe pendant que vous êtes occupé à faire d\'autres projets.', author: 'John Lennon' },
  { id: 'q9', text: 'Un voyage de mille lieues commence toujours par un premier pas.', author: 'Lao Tseu' },
  { id: 'q10', text: 'Il n\'y a qu\'une façon d\'échouer, c\'est d\'abandonner avant d\'avoir réussi.', author: 'Georges Clemenceau' },
  { id: 'q11', text: 'Le meilleur moment pour planter un arbre était il y a 20 ans. Le deuxième meilleur moment est maintenant.', author: 'Proverbe chinois' },
  { id: 'q12', text: 'Vous êtes plus proche de votre objectif que vous ne le pensez.', author: 'Inconnu' },
];

export const HABIT_COLORS = [
  '#ef4444', '#f97316', '#f59e0b', '#eab308',
  '#84cc16', '#22c55e', '#14b8a6', '#06b6d4',
  '#3b82f6', '#6366f1', '#8b5cf6', '#a855f7',
  '#d946ef', '#ec4899', '#f43f5e', '#78716c',
];

export const HABIT_ICONS = [
  '🏃', '💪', '🧘', '📖', '✍️', '🎯', '💧', '🍎',
  '💤', '🧠', '🎵', '🎨', '💻', '📝', '🏋️', '🚴',
  '🧹', '🌱', '📱', '💤', '🎯', '📚', '🎓', '🍳',
  '🎸', '📷', '🏋', '🤸', '🧗', '🏄', '🚶', '🧘‍♂️',
  '🎓', '✏️', '💡', '🔬', '🗣️', '🤝', '❤️', '🌍',
  '💰', '📊', '🛒', '🏠', '🚗', '⏰', '🎮', '🎭',
];

export const PROPOSED_HABITS = [
  { name: 'Boire 8 verres d\'eau', icon: '💧', color: '#06b6d4', categories: ['sante', 'forme'] },
  { name: 'Méditer 10 minutes', icon: '🧘', color: '#8b5cf6', categories: ['mental', 'forme'] },
  { name: 'Lire 20 pages', icon: '📖', color: '#22c55e', categories: ['reading'] },
  { name: 'Faire de l\'exercice', icon: '🏃', color: '#ef4444', categories: ['sports'] },
  { name: 'Journal de gratitude', icon: '✍️', color: '#f59e0b', categories: ['other'] },
  { name: 'Apprendre quelque chose', icon: '🎓', color: '#3b82f6', categories: ['coding', 'reading'] },
  { name: 'Dormir avant 23h', icon: '💤', color: '#6366f1', categories: ['other'] },
  { name: 'Manger sainement', icon: '🍎', color: '#22c55e', categories: ['cooking'] },
  { name: 'Pratiquer un instrument', icon: '🎵', color: '#ec4899', categories: ['music'] },
  { name: 'Dessiner ou peindre', icon: '🎨', color: '#f97316', categories: ['art'] },
  { name: 'Coder 30 minutes', icon: '💻', color: '#14b8a6', categories: ['coding'] },
  { name: 'Écrire', icon: '📝', color: '#84cc16', categories: ['art', 'reading'] },
  { name: 'Étirer / Yoga', icon: '🧘‍♂️', color: '#a855f7', categories: ['sports'] },
  { name: 'Cuisiner un repas', icon: '🍳', color: '#f43f5e', categories: ['cooking'] },
  { name: 'Marcher 10 000 pas', icon: '🚶', color: '#eab308', categories: ['sports'] },
  { name: 'Jouer à un jeu', icon: '🎮', color: '#78716c', categories: ['gaming'] },
];

export const THEMES = {
  midnight: {
    name: 'Minuit',
    emoji: '🌙',
    vars: {
      '--background': '#0f172a',
      '--foreground': '#f8fafc',
      '--card': '#1e293b',
      '--card-foreground': '#f8fafc',
      '--popover': '#1e293b',
      '--popover-foreground': '#f8fafc',
      '--primary': '#818cf8',
      '--primary-foreground': '#0f172a',
      '--secondary': '#334155',
      '--secondary-foreground': '#f8fafc',
      '--muted': '#334155',
      '--muted-foreground': '#94a3b8',
      '--accent': '#334155',
      '--accent-foreground': '#f8fafc',
      '--destructive': '#f87171',
      '--border': '#334155',
      '--input': '#334155',
      '--ring': '#818cf8',
      '--chart-1': '#818cf8',
      '--chart-2': '#34d399',
      '--chart-3': '#fbbf24',
      '--chart-4': '#f87171',
      '--chart-5': '#a78bfa',
    },
  },
  ocean: {
    name: 'Océan',
    emoji: '🌊',
    vars: {
      '--background': '#0c4a6e',
      '--foreground': '#ecfeff',
      '--card': '#0e7490',
      '--card-foreground': '#ecfeff',
      '--popover': '#0e7490',
      '--popover-foreground': '#ecfeff',
      '--primary': '#22d3ee',
      '--primary-foreground': '#0c4a6e',
      '--secondary': '#155e75',
      '--secondary-foreground': '#ecfeff',
      '--muted': '#155e75',
      '--muted-foreground': '#67e8f9',
      '--accent': '#155e75',
      '--accent-foreground': '#ecfeff',
      '--destructive': '#fb7185',
      '--border': '#155e75',
      '--input': '#155e75',
      '--ring': '#22d3ee',
      '--chart-1': '#22d3ee',
      '--chart-2': '#a5f3fc',
      '--chart-3': '#67e8f9',
      '--chart-4': '#fbbf24',
      '--chart-5': '#fb7185',
    },
  },
  forest: {
    name: 'Forêt',
    emoji: '🌲',
    vars: {
      '--background': '#14532d',
      '--foreground': '#f0fdf4',
      '--card': '#166534',
      '--card-foreground': '#f0fdf4',
      '--popover': '#166534',
      '--popover-foreground': '#f0fdf4',
      '--primary': '#4ade80',
      '--primary-foreground': '#14532d',
      '--secondary': '#15803d',
      '--secondary-foreground': '#f0fdf4',
      '--muted': '#15803d',
      '--muted-foreground': '#86efac',
      '--accent': '#15803d',
      '--accent-foreground': '#f0fdf4',
      '--destructive': '#f87171',
      '--border': '#15803d',
      '--input': '#15803d',
      '--ring': '#4ade80',
      '--chart-1': '#4ade80',
      '--chart-2': '#fbbf24',
      '--chart-3': '#a78bfa',
      '--chart-4': '#fb923c',
      '--chart-5': '#38bdf8',
    },
  },
  sunset: {
    name: 'Coucher de soleil',
    emoji: '🌅',
    vars: {
      '--background': '#431407',
      '--foreground': '#fff7ed',
      '--card': '#7c2d12',
      '--card-foreground': '#fff7ed',
      '--popover': '#7c2d12',
      '--popover-foreground': '#fff7ed',
      '--primary': '#fb923c',
      '--primary-foreground': '#431407',
      '--secondary': '#9a3412',
      '--secondary-foreground': '#fff7ed',
      '--muted': '#9a3412',
      '--muted-foreground': '#fdba74',
      '--accent': '#9a3412',
      '--accent-foreground': '#fff7ed',
      '--destructive': '#f87171',
      '--border': '#9a3412',
      '--input': '#9a3412',
      '--ring': '#fb923c',
      '--chart-1': '#fb923c',
      '--chart-2': '#fbbf24',
      '--chart-3': '#a78bfa',
      '--chart-4': '#34d399',
      '--chart-5': '#f87171',
    },
  },
  lavender: {
    name: 'Lavande',
    emoji: '💜',
    vars: {
      '--background': '#2e1065',
      '--foreground': '#faf5ff',
      '--card': '#4c1d95',
      '--card-foreground': '#faf5ff',
      '--popover': '#4c1d95',
      '--popover-foreground': '#faf5ff',
      '--primary': '#c084fc',
      '--primary-foreground': '#2e1065',
      '--secondary': '#5b21b6',
      '--secondary-foreground': '#faf5ff',
      '--muted': '#5b21b6',
      '--muted-foreground': '#d8b4fe',
      '--accent': '#5b21b6',
      '--accent-foreground': '#faf5ff',
      '--destructive': '#f87171',
      '--border': '#5b21b6',
      '--input': '#5b21b6',
      '--ring': '#c084fc',
      '--chart-1': '#c084fc',
      '--chart-2': '#f0abfc',
      '--chart-3': '#fbbf24',
      '--chart-4': '#34d399',
      '--chart-5': '#fb923c',
    },
  },
  rose: {
    name: 'Rose',
    emoji: '🌹',
    vars: {
      '--background': '#4c0519',
      '--foreground': '#fff1f2',
      '--card': '#881337',
      '--card-foreground': '#fff1f2',
      '--popover': '#881337',
      '--popover-foreground': '#fff1f2',
      '--primary': '#fb7185',
      '--primary-foreground': '#4c0519',
      '--secondary': '#9f1239',
      '--secondary-foreground': '#fff1f2',
      '--muted': '#9f1239',
      '--muted-foreground': '#fda4af',
      '--accent': '#9f1239',
      '--accent-foreground': '#fff1f2',
      '--destructive': '#fbbf24',
      '--border': '#9f1239',
      '--input': '#9f1239',
      '--ring': '#fb7185',
      '--chart-1': '#fb7185',
      '--chart-2': '#fda4af',
      '--chart-3': '#c084fc',
      '--chart-4': '#67e8f9',
      '--chart-5': '#4ade80',
    },
  },
  slate: {
    name: 'Ardoise',
    emoji: '🪨',
    vars: {
      '--background': '#0f172a',
      '--foreground': '#f8fafc',
      '--card': '#1e293b',
      '--card-foreground': '#f8fafc',
      '--popover': '#1e293b',
      '--popover-foreground': '#f8fafc',
      '--primary': '#f8fafc',
      '--primary-foreground': '#0f172a',
      '--secondary': '#334155',
      '--secondary-foreground': '#f8fafc',
      '--muted': '#334155',
      '--muted-foreground': '#94a3b8',
      '--accent': '#334155',
      '--accent-foreground': '#f8fafc',
      '--destructive': '#f87171',
      '--border': '#334155',
      '--input': '#334155',
      '--ring': '#f8fafc',
      '--chart-1': '#94a3b8',
      '--chart-2': '#38bdf8',
      '--chart-3': '#4ade80',
      '--chart-4': '#fbbf24',
      '--chart-5': '#fb923c',
    },
  },
  custom: {
    name: 'Personnalisé',
    emoji: '🎨',
    vars: {},
  },
} as const;

export const XP_PER_LEVEL = 500;
